name: Assign issues to Jezza34000

on:
  issues:
    types:
      - opened
      - reopened

permissions:
  issues: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to Jezza34000
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: Jezza34000
