name: Label issues based on template

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add Bug label
        if: contains(github.event.issue.body, 'Rapport de bug')
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-label "Bug"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Feature label
        if: contains(github.event.issue.body, 'Demande de nouvelle fonctionnalité')
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-label "Feature Request"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
